title: Ruchil Barya # your name (or website title) here
logo: "/images/1612811738206.jpg?raw=true" # your photo (or logo) here
description: 

<p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/ruchil-barya-1770867b/">LinkedIn</a> |
  <a href="https://github.com/ruchilbarya">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing MS degree in Analytics at Harrisburg University of Science and Technology.
  <br><br>
  I am currently a Machine Learning Research Intern at ASCII labs with a focus on NLP and Deep Learning research.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
